name: FTP Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0  # Check for the latest version
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}  # Optional
          local-dir: ./ # Adjust if your files are in a subdirectory
          remote-dir: ./htdocs
          protocol: ftps  # Change to ftp if you're not using FTPS
          debug: true  # Enable debug mode